version: '3'
services:
  postgresql:
    image: postgres:12.2-alpine
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - "./myvol/pgdata:/pgdata"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: "/pgdata"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"

  nodejs:
    build: .
    container_name: nodejs
    ports:
      - "8000:8000"
    volumes:
      - "./myvol/workdir:/workdir"
    command: [sh, -c, yarn install && PORT=8000 yarn start]